class MotorParams():
    def __init__(self):
        
        self.params = {
            'position_measured':    0.,
            'position_target':      0.,
            'velocity_measured':    0.,
            'velocity_target':      0.,
            'torque_measured':      0.,
            'torque_target':        0.,
            'iq_measured':          0.,
            'iq_target':            0.,
            'id_measured':          0.,
            'id_target':            0.,
            'vq_measured':          0.,
            'vq_target':            0.,
            'vd_measured':          0.,
            'vd_target':            0.,
            'position_kp':          0.,
            'position_ki':          0.,
            'position_kd':          0.,
            'current_kp':           0.,
            'current_ki':           0.,
            'v_bus':                0.,
            'position_limit_lower': 0.,
            'position_limit_upper': 0.,
            'velocity_limit_lower': 0.,
            'velocity_limit_upper': 0.,
            'torque_limit_lower':   0.,
            'torque_limit_upper':   0.,
            'pole_pairs':           0.,
            'kv':                   0.,
            'gear_ratio':           0.,
        }

        self.can2params = {
            'CAN_ID_POSITION_MEASURED':     ['position_measured'],
            'CAN_ID_POSITION_TARGET':       ['position_target'],
            'CAN_ID_VELOCITY_MEASURED':     ['velocity_measured'],
            'CAN_ID_VELOCITY_TARGET':       ['velocity_target'],
            'CAN_ID_TORQUE_MEASURED':       ['torque_measured'],
            'CAN_ID_TORQUE_TARGET':         ['torque_target'],
            'CAN_ID_POSITION_LIMIT':        ['position_limit_lower', 'position_limit_upper'],
            'CAN_ID_VELOCITY_LIMIT':        ['velocity_limit_lower', 'velocity_limit_upper'],
            'CAN_ID_TORQUE_LIMIT':          ['torque_limit_lower', 'torque_limit_upper'],
            'CAN_ID_CURRENTCONTROLLER_IQ':  ['iq_target', 'iq_measured'],
            'CAN_ID_CURRENTCONTROLLER_ID':  ['id_target', 'id_measured'],
            'CAN_ID_CURRENTCONTROLLER_VQ':  ['vq_target', 'vq_measured'],
            'CAN_ID_CURRENTCONTROLLER_VD':  ['vd_target', 'vd_measured'],
            'CAN_ID_BUS_VOLTAGE':           ['v_bus'],
            'CAN_ID_IQ_KP_KI':              ['current_kp', 'current_ki'],
            'CAN_ID_POSITION_KP_KD':        ['position_kp', 'position_kd'],
            'CAN_ID_POSITION_KI':           ['position_ki'],
            'CAN_ID_MOTOR_SPEC':            ['pole_pairs', 'kv']
        }